import type { Metadata } from "next";
import { Coda, Geist_Mono } from "next/font/google";
import "./globals.css";

const coda = Coda({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${coda.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
